---
name: Release

on:
  push:

jobs:
  lint_repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip3 install yamllint ansible-lint ansible

      - run: yamllint .

      - run: ansible-lint

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
      